server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /projects {
        proxy_pass http://back:3000;
    }

    location /tasks {
        proxy_pass http://back:3000;
    }
}