services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    depends_on:
      - database

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: projet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local